"""Seed the shared SQLite DB with a realistic mock semiconductor-fab dataset.

    python -m mes_core.seed

Reproducible: resets all tables and regenerates the same dataset every time
(fixed RNG seed). Master data is inserted directly; dynamic data (lots, process
results, inventory, product results) is generated by calling the real
transaction functions so the snapshot is internally consistent.
"""

from __future__ import annotations

import random

from . import db

# (product_code, product_name, tech_node)
PRODUCTS = [
    ("LX9", "LX9 AP", "5nm"),
    ("DDR5", "DDR5-16G", "10nm"),
    ("NAND", "V7 NAND", "128L"),
    ("PMIC", "PMIC-33", "28nm"),
]

# (seq, step_code, step_name, operation, eqp_type, stage)
ROUTE = [
    (10, "DIFF",  "Diffusion",           "Thermal Oxidation",          "Furnace",   "FAB"),
    (20, "PHOTO", "Photolithography",    "Pattern Exposure",           "Scanner",   "FAB"),
    (30, "ETCH",  "Etch",                "Plasma Etch",                "Etcher",    "FAB"),
    (40, "IMPL",  "Ion Implant",         "Dopant Implant",             "Implanter", "FAB"),
    (50, "CVD",   "Deposition (CVD)",    "Thin-Film Deposition",       "CVD",       "FAB"),
    (60, "CMP",   "Planarization (CMP)", "Chemical-Mechanical Polish", "Polisher",  "FAB"),
    (70, "METRO", "Metrology",           "Inline Inspection",          "Metrology", "FAB"),
    (80, "TEST",  "Wafer Test (EDS)",    "Electrical Die Sort",        "Prober",    "FAB"),
    (90, "PKG",   "Packaging",           "Assembly & Test",            "Bonder",    "PACK"),
]

# (eqp_id, eqp_name, type, status)
EQUIPMENT = [
    ("EQP-DIFF01", "Furnace-A",    "Furnace",   "Run"),
    ("EQP-PHOT01", "Scanner-EUV1", "Scanner",   "Run"),
    ("EQP-PHOT02", "Scanner-DUV1", "Scanner",   "Idle"),
    ("EQP-ETCH01", "Etcher-A",     "Etcher",    "Run"),
    ("EQP-IMPL01", "Implanter-A",  "Implanter", "Down"),
    ("EQP-CVD01",  "CVD-A",        "CVD",       "Run"),
    ("EQP-CMP01",  "Polisher-A",   "Polisher",  "Idle"),
    ("EQP-TEST01", "Prober-A",     "Prober",    "Run"),
    ("EQP-PKG01",  "Bonder-A",     "Bonder",    "Run"),
]

# (material_code, material_name, category, qty, uom, location)
MATERIALS = [
    ("RAW-WAFER-300", "300mm Blank Silicon Wafer", "Raw Wafer", 12000, "EA",  "WH-RAW"),
    ("RETICLE-5NM",   "EUV Reticle Set (5nm)",     "Mask",         45, "SET", "WH-MASK"),
    ("PR-EUV",        "EUV Photoresist",           "Chemical",    320, "L",   "WH-CHEM"),
    ("SLURRY-CMP",    "CMP Slurry",                "Chemical",    500, "L",   "WH-CHEM"),
    ("GAS-SIH4",      "Silane (SiH4) Gas",         "Gas",         180, "BTL", "WH-GAS"),
    ("GAS-AR",        "Argon (Ar) Gas",            "Gas",         400, "BTL", "WH-GAS"),
    ("TARGET-CU",     "Copper Sputter Target",     "Metal",        60, "EA",  "WH-MAT"),
    ("DOPANT-B",      "Boron Dopant Source",       "Chemical",     90, "L",   "WH-CHEM"),
    ("SUBSTRATE",     "BGA Package Substrate",     "Package",    8000, "EA",  "WH-PKG"),
    ("BOND-WIRE",     "Gold Bond Wire",            "Package",   50000, "M",   "WH-PKG"),
    ("MOLD-EMC",      "Epoxy Mold Compound",       "Package",     600, "KG",  "WH-PKG"),
    ("SOLDER-BALL",   "SnAg Solder Ball",          "Package",   90000, "EA",  "WH-PKG"),
]

# BOM template shared by all products: (step_code, material_code, qty_per_wafer, uom)
FAB_BOM = [
    ("DIFF",  "RAW-WAFER-300", 1.0,  "EA"),
    ("DIFF",  "GAS-AR",        0.05, "BTL"),
    ("PHOTO", "PR-EUV",        0.20, "L"),
    ("ETCH",  "GAS-AR",        0.10, "BTL"),
    ("IMPL",  "DOPANT-B",      0.08, "L"),
    ("CVD",   "GAS-SIH4",      0.15, "BTL"),
    ("CMP",   "SLURRY-CMP",    0.25, "L"),
]
PKG_BOM = [
    ("PKG", "SUBSTRATE",   1.0,  "EA"),
    ("PKG", "BOND-WIRE",   40.0, "M"),
    ("PKG", "MOLD-EMC",    0.02, "KG"),
    ("PKG", "SOLDER-BALL", 80.0, "EA"),
]

PRIORITIES = ["Hot", "Normal", "Normal", "Normal", "Low"]
OPERATORS = ["kim.js", "lee.mh", "park.sy", "choi.dw", "jung.hy"]
DEFECTS = ["Particle", "Scratch", "Overlay", "CD-OOS", "Etch-Residue", "Contamination"]

FAB_STEPS = [r[1] for r in ROUTE if r[5] == "FAB"]  # DIFF..TEST in order
STEP_EQP_TYPE = {code: eqp_type for _, code, _, _, eqp_type, _ in ROUTE}
EQP_BY_TYPE: dict[str, list[str]] = {}
for _eid, _name, _type, _status in EQUIPMENT:
    EQP_BY_TYPE.setdefault(_type, []).append(_eid)


def _pick_eqp(step_code: str, rnd: random.Random):
    choices = EQP_BY_TYPE.get(STEP_EQP_TYPE.get(step_code), [])
    return rnd.choice(choices) if choices else None


def _scrap_for(step_code: str, in_qty: int, rnd: random.Random) -> int:
    if in_qty <= 0 or rnd.random() < 0.6:
        return 0
    high = step_code in ("ETCH", "IMPL", "TEST")
    return min(in_qty, rnd.randint(1, 3 if high else 2))


def _insert_master() -> None:
    with db.get_conn() as conn:
        conn.executemany("INSERT INTO product VALUES (?,?,?)", PRODUCTS)
        conn.executemany(
            "INSERT INTO process_step (seq, step_code, step_name, operation, eqp_type, stage)"
            " VALUES (?,?,?,?,?,?)",
            ROUTE,
        )
        conn.executemany("INSERT INTO equipment VALUES (?,?,?,?)", EQUIPMENT)
        conn.executemany(
            "INSERT INTO material (material_code, material_name, category, qty, uom, location)"
            " VALUES (?,?,?,?,?,?)",
            MATERIALS,
        )
        bom_rows = []
        for pcode, _pn, _tn in PRODUCTS:
            for step, mat, qpw, uom in FAB_BOM + PKG_BOM:
                bom_rows.append((pcode, step, mat, qpw, uom))
            # one product-specific metal usage to vary the BOM
            bom_rows.append((pcode, "CVD", "TARGET-CU", 0.02, "EA"))
        conn.executemany(
            "INSERT INTO bom (product_code, step_code, material_code, qty_per_wafer, uom)"
            " VALUES (?,?,?,?,?)",
            bom_rows,
        )


def _advance(lot_id: str, upto_idx: int, rnd: random.Random) -> None:
    """Move a lot through FAB_STEPS[0..upto_idx] inclusive, with occasional scrap."""
    for idx in range(upto_idx + 1):
        step = FAB_STEPS[idx]
        lot = db.get_lot(lot_id)
        in_qty = lot["wafer_qty"]
        scrap = _scrap_for(step, in_qty, rnd)
        defect = rnd.choice(DEFECTS) if scrap > 0 else None
        result = "Pass" if rnd.random() > 0.05 else rnd.choice(["Rework", "Fail"])
        # ensure the final TEST step passes so Done lots produce SEMI
        if step == "TEST":
            result = "Pass"
        db.register_process_result(
            lot_id, step, eqp_id=_pick_eqp(step, rnd), in_qty=in_qty,
            scrap_qty=scrap, defect_code=defect,
            operator=rnd.choice(OPERATORS), result=result,
        )


def seed() -> None:
    rnd = random.Random(42)
    db.reset_db()
    _insert_master()

    done_products: list[str] = []
    for i in range(1, 17):
        pcode, _pn, _tn = PRODUCTS[(i - 1) % len(PRODUCTS)]
        start_qty = rnd.choice([25, 25, 25, 24, 12])
        priority = rnd.choice(PRIORITIES)
        lot = db.start_lot(pcode, start_qty, priority=priority)
        lot_id = lot["lot_id"]
        if i <= 6:                       # Done: full FAB route (TEST passes -> SEMI)
            _advance(lot_id, len(FAB_STEPS) - 1, rnd)
            done_products.append(pcode)
        elif i <= 8:                     # Hold: partway then held
            _advance(lot_id, rnd.randint(1, 5), rnd)
            with db.get_conn() as conn:
                conn.execute("UPDATE lot SET status='Hold' WHERE lot_id=?", (lot_id,))
        else:                            # Running: partway
            _advance(lot_id, rnd.randint(0, 6), rnd)

    # Package 3 of the completed products (consume SEMI -> FIN)
    for pcode in done_products[:3]:
        semi = db.list_product_inventory(product_code=pcode, item_type="SEMI")
        avail = int(semi[0]["qty"]) if semi else 0
        if avail > 0:
            db.package(pcode, max(1, avail // 2), scrap_qty=rnd.randint(0, 1),
                       eqp_id="EQP-PKG01", operator=rnd.choice(OPERATORS))

    # One manual FIN result against a Done lot
    done_lots = db.list_lots(status="Done")
    if done_lots:
        db.register_product_result(done_lots[0]["lot_id"], "FIN", rnd.randint(100, 400))


def main() -> None:
    path = db.get_db_path()
    seed()
    c = db.counts()
    print(f"[seed] mock MES database ready at {path}")
    print("[seed] rows: " + ", ".join(f"{k}={v}" for k, v in c.items()))


if __name__ == "__main__":
    main()
